import type {SurveySession, SurveyPhoto, VoiceObservation, Measurement} from "../features/survey/slice/survey.type.ts";

export const MOCK_SURVEY_SESSION: SurveySession = {
    id: 'session-1',
    buildingId: 'building-1',
    technicianId: '1',
    deviceInfo: {
        userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X)',
        platform: 'iPhone',
        screenWidth: 390,
        screenHeight: 844,
        hasCamera: true,
        hasMicrophone: true,
        hasGeolocation: true,
        hasDeviceOrientation: true,
    },
    startedAt: '2026-08-01T09:00:00Z',
    status: 'active',
    softwareVersion: '1.0.0',
};

export const MOCK_PHOTOS: SurveyPhoto[] = [
    {
        id: 'photo-1',
        sessionId: 'session-1',
        timestamp: '2026-08-01T09:05:30Z',
        floorId: 'floor-1',
        roomId: 'room-1',
        targetElementId: 'wall-1',
        geolocation: {lat: 45.4642, lon: 9.1900, accuracy: 5, timestamp: 1753945530000},
        deviceOrientation: {alpha: 180, beta: 90, gamma: 0},
        confidence: 92,
        dataStatus: 'VALIDATED',
        mediaPath: '/uploads/session-1/photo-1.jpg',
        thumbnailPath: '/uploads/session-1/thumb-photo-1.jpg',
        viewDirection: 'nord',
    },
    {
        id: 'photo-2',
        sessionId: 'session-1',
        timestamp: '2026-08-01T09:10:15Z',
        floorId: 'floor-1',
        roomId: 'room-2',
        targetElementId: 'window-1',
        geolocation: {lat: 45.4642, lon: 9.1901, accuracy: 8, timestamp: 1753945815000},
        confidence: 78,
        dataStatus: 'PROPOSED',
        mediaPath: '/uploads/session-1/photo-2.jpg',
        thumbnailPath: '/uploads/session-1/thumb-photo-2.jpg',
        viewDirection: 'sud',
    },
    {
        id: 'photo-3',
        sessionId: 'session-1',
        timestamp: '2026-08-01T09:14:00Z',
        floorId: 'floor-1',
        roomId: 'room-2',
        targetElementId: 'defect-1',
        confidence: 85,
        dataStatus: 'PROPOSED',
        mediaPath: '/uploads/session-1/photo-3.jpg',
        viewDirection: 'est',
    },
];

export const MOCK_VOICE_OBSERVATIONS: VoiceObservation[] = [
    {
        id: 'voice-1',
        sessionId: 'session-1',
        timestamp: '2026-08-01T09:06:00Z',
        audioPath: '/uploads/session-1/voice-1.webm',
        transcription: 'Parete nord ingresso, laterizio intonacato, buone condizioni generali',
        floorId: 'floor-1',
        roomId: 'room-1',
        targetElementId: 'wall-1',
        confidence: 88,
        dataStatus: 'VALIDATED',
    },
    {
        id: 'voice-2',
        sessionId: 'session-1',
        timestamp: '2026-08-01T09:14:30Z',
        audioPath: '/uploads/session-1/voice-2.webm',
        transcription: 'Crepa sulla parete est della cucina, circa quaranta centimetri, sembra da assestamento',
        floorId: 'floor-1',
        roomId: 'room-2',
        targetElementId: 'defect-1',
        confidence: 82,
        dataStatus: 'PROPOSED',
    },
];

export const MOCK_MEASUREMENTS: Measurement[] = [
    {
        id: 'measure-1',
        sessionId: 'session-1',
        type: 'distance',
        value: 4.2,
        unit: 'm',
        elementId: 'wall-1',
        timestamp: '2026-08-01T09:06:30Z',
        confidence: 95,
        dataStatus: 'VALIDATED',
    },
    {
        id: 'measure-2',
        sessionId: 'session-1',
        type: 'height',
        value: 3.0,
        unit: 'm',
        elementId: 'room-1',
        timestamp: '2026-08-01T09:07:00Z',
        confidence: 90,
        dataStatus: 'VALIDATED',
    },
    {
        id: 'measure-3',
        sessionId: 'session-1',
        type: 'thickness',
        value: 25,
        unit: 'cm',
        elementId: 'wall-2',
        instrumentId: 'laser-1',
        timestamp: '2026-08-01T09:12:00Z',
        confidence: 72,
        dataStatus: 'PROPOSED',
    },
];
