import type {BuildingCardData} from "../features/buildings/buildings.type.ts";

export const MOCK_BUILDINGS: BuildingCardData[] = [
    {
        id: 'building-1',
        name: 'Municipio di Vignola',
        address: 'Piazza dei Contrari, 1',
        city: 'Vignola',
        buildingType: 'Municipio',
        floorsCount: 4,
        completionPercent: 92,
        criticalityCount: 2,
        createdAt: '2026-08-15T10:30:00.000Z',
        deadline: '2026-12-11',
        status: 'active',
    },
    {
        id: 'building-2',
        name: 'Scuola Primaria G. Mazzini',
        address: 'Via Mazzini, 12',
        city: 'Vignola',
        buildingType: 'Scuola',
        floorsCount: 2,
        completionPercent: 85,
        criticalityCount: 1,
        createdAt: '2026-08-20T14:00:00.000Z',
        deadline: '2026-12-09',
        status: 'active',
    },
    {
        id: 'building-3',
        name: 'Palazzetto dello Sport',
        address: 'Via dello Sport, 5',
        city: 'Vignola',
        buildingType: 'Impianto sportivo',
        floorsCount: 1,
        completionPercent: 78,
        criticalityCount: 3,
        createdAt: '2026-08-28T09:15:00.000Z',
        deadline: '2026-11-22',
        status: 'active',
    },
    {
        id: 'building-4',
        name: 'Rocca di Vignola',
        address: 'Piazza dei Contrari',
        city: 'Vignola',
        buildingType: 'Edificio storico',
        floorsCount: 3,
        completionPercent: 88,
        criticalityCount: 1,
        createdAt: '2026-09-01T11:00:00.000Z',
        deadline: '2027-01-15',
        status: 'active',
    },
    {
        id: 'building-5',
        name: 'Biblioteca Comunale F. Selmi',
        address: 'Via Bonesi, 3',
        city: 'Vignola',
        buildingType: 'Cultura',
        floorsCount: 2,
        completionPercent: 83,
        criticalityCount: 0,
        createdAt: '2026-07-10T08:00:00.000Z',
        status: 'completed',
    },
    {
        id: 'building-6',
        name: 'Centro Anziani',
        address: 'Via Libertà, 22',
        city: 'Vignola',
        buildingType: 'Sociale',
        floorsCount: 1,
        completionPercent: 68,
        criticalityCount: 4,
        createdAt: '2026-09-01T11:00:00.000Z',
        status: 'draft',
    },
];
