import type {BuildingElement} from "../features/building/slice/building.type.ts";

export const MOCK_BUILDING_ELEMENTS: BuildingElement[] = [
    {
        id: 'building-1',
        label: 'Edificio Via Roma 10',
        parentId: null,
        type: 'building',
        dataStatus: 'VALIDATED',
        confidence: 100,
        sessionId: 'session-1',
        createdAt: '2026-08-01T09:00:00Z',
        updatedAt: '2026-08-01T09:00:00Z',
        address: 'Via Roma 10, Milano',
        floors: ['floor-1', 'floor-2'],
    },
    {
        id: 'floor-1',
        label: 'Piano Terra',
        parentId: 'building-1',
        type: 'floor',
        dataStatus: 'VALIDATED',
        confidence: 100,
        sessionId: 'session-1',
        createdAt: '2026-08-01T09:00:00Z',
        updatedAt: '2026-08-01T09:00:00Z',
        floorNumber: 0,
        rooms: ['room-1', 'room-2'],
    },
    {
        id: 'floor-2',
        label: 'Primo Piano',
        parentId: 'building-1',
        type: 'floor',
        dataStatus: 'VALIDATED',
        confidence: 100,
        sessionId: 'session-1',
        createdAt: '2026-08-01T09:00:00Z',
        updatedAt: '2026-08-01T09:00:00Z',
        floorNumber: 1,
        rooms: ['room-3'],
    },
    {
        id: 'room-1',
        label: 'Ingresso',
        parentId: 'floor-1',
        type: 'room',
        dataStatus: 'VALIDATED',
        confidence: 95,
        sessionId: 'session-1',
        createdAt: '2026-08-01T09:05:00Z',
        updatedAt: '2026-08-01T09:05:00Z',
        area: 12.5,
        perimeter: 14.2,
        height: 3.0,
        elements: ['wall-1', 'door-1'],
    },
    {
        id: 'room-2',
        label: 'Cucina',
        parentId: 'floor-1',
        type: 'room',
        dataStatus: 'PROPOSED',
        confidence: 82,
        sessionId: 'session-1',
        createdAt: '2026-08-01T09:10:00Z',
        updatedAt: '2026-08-01T09:10:00Z',
        area: 18.0,
        perimeter: 17.6,
        height: 3.0,
        elements: ['wall-2', 'window-1', 'plant-1', 'defect-1'],
    },
    {
        id: 'room-3',
        label: 'Camera da letto',
        parentId: 'floor-2',
        type: 'room',
        dataStatus: 'RAW',
        confidence: 60,
        sessionId: 'session-1',
        createdAt: '2026-08-01T09:20:00Z',
        updatedAt: '2026-08-01T09:20:00Z',
        area: 22.0,
        perimeter: 19.0,
        height: 2.9,
        elements: ['window-2'],
    },
    {
        id: 'wall-1',
        label: 'Parete nord ingresso',
        parentId: 'room-1',
        type: 'wall',
        dataStatus: 'VALIDATED',
        confidence: 90,
        sessionId: 'session-1',
        createdAt: '2026-08-01T09:06:00Z',
        updatedAt: '2026-08-01T09:06:00Z',
        length: 4.2,
        height: 3.0,
        thickness: 0.3,
        material: 'Laterizio',
    },
    {
        id: 'wall-2',
        label: 'Parete est cucina',
        parentId: 'room-2',
        type: 'wall',
        dataStatus: 'PROPOSED',
        confidence: 75,
        sessionId: 'session-1',
        createdAt: '2026-08-01T09:11:00Z',
        updatedAt: '2026-08-01T09:11:00Z',
        length: 5.0,
        height: 3.0,
        thickness: 0.25,
        material: 'Cartongesso',
    },
    {
        id: 'door-1',
        label: 'Porta ingresso principale',
        parentId: 'room-1',
        type: 'door',
        dataStatus: 'VALIDATED',
        confidence: 95,
        sessionId: 'session-1',
        createdAt: '2026-08-01T09:07:00Z',
        updatedAt: '2026-08-01T09:07:00Z',
        width: 0.9,
        height: 2.1,
        material: 'Legno',
        openingDirection: 'right',
    },
    {
        id: 'window-1',
        label: 'Finestra cucina sud',
        parentId: 'room-2',
        type: 'window',
        dataStatus: 'PROPOSED',
        confidence: 78,
        sessionId: 'session-1',
        createdAt: '2026-08-01T09:12:00Z',
        updatedAt: '2026-08-01T09:12:00Z',
        width: 1.2,
        height: 1.4,
        sillHeight: 0.9,
        material: 'PVC',
        glazingType: 'double',
    },
    {
        id: 'window-2',
        label: 'Finestra camera nord',
        parentId: 'room-3',
        type: 'window',
        dataStatus: 'RAW',
        confidence: 55,
        sessionId: 'session-1',
        createdAt: '2026-08-01T09:21:00Z',
        updatedAt: '2026-08-01T09:21:00Z',
        width: 1.4,
        height: 1.6,
        sillHeight: 0.85,
        material: 'Alluminio',
        glazingType: 'triple',
    },
    {
        id: 'plant-1',
        label: 'Impianto idraulico cucina',
        parentId: 'room-2',
        type: 'plant',
        dataStatus: 'PROPOSED',
        confidence: 70,
        sessionId: 'session-1',
        createdAt: '2026-08-01T09:13:00Z',
        updatedAt: '2026-08-01T09:13:00Z',
        plantType: 'plumbing',
        description: 'Tubazioni acqua calda/fredda sotto il lavello',
    },
    {
        id: 'defect-1',
        label: 'Crepa parete est cucina',
        parentId: 'room-2',
        type: 'defect',
        dataStatus: 'PROPOSED',
        confidence: 85,
        sessionId: 'session-1',
        createdAt: '2026-08-01T09:14:00Z',
        updatedAt: '2026-08-01T09:14:00Z',
        severity: 'medium',
        description: 'Crepa diagonale di circa 40cm sulla parete est, probabilmente da assestamento',
        photoIds: ['photo-3'],
    },
];
