import {User} from "../features/auth/slice/auth.type.ts";

export const MOCK_USER: Partial<User> = {
    id: '1',
    role: 'owner',
    company_id: '1',
    code_tax: 'DMNADM80A01H501Z',
    dob: '1980-01-01',
    first_name: 'Admin',
    last_name: 'User',
    email: 'admin@boilerplate.com',
    email_verified_at: '2024-01-01T00:00:00Z',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    name: 'Admin User',
    short_name: 'AU',
    avatar: '',
    username: 'admin',
    password: '',
    surname: 'User',
    addr_street: '',
    addr_zip: '',
    addr_city: '',
    addr_province: '',
    addr_country: '',
    addr_notes: '',
    relations: {
        company: {
            id: '1',
            name: 'Boilerplate Company',
            code_vat: '12345678901',
            code_tax: '12345678901',
            first_name: '',
            last_name: '',
            type: 'a',
            code_sdi: '',
            code_ateco: '',
            code_ateco_2: '',
            email: 'info@boilerplate.com',
            phone: '',
            pec: '',
            licensed_from: '2024-01-01',
            licensed_to: '2030-12-31',
            user_ctx: {is_licensed: true},
            created_at: '2024-01-01T00:00:00Z',
            updated_at: '2024-01-01T00:00:00Z',
            addr_street: '',
            addr_zip: '',
            addr_city: '',
            addr_province: '',
            addr_country: '',
            addr_notes: '',
        },
        attachments: {}
    },
};
